const ShopActionTypes = {
  STORE_UNSUBSCRIBE_FROM_SNAPSHOT: "STORE_UNSUBSCRIBE_FROM_SNAPSHOT",
  CALL_UNSUBSCRIBE_FROM_SNAPSHOT: "CALL_UNSUBSCRIBE_FROM_SNAPSHOT",
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
};

export default ShopActionTypes;
