export const UserActionTypes = {
  STORE_UNSUBSCRIBE_FROM_AUTH: "STORE_UNSUBSCRIBE_FROM_AUTH",
  CALL_UNSUBSCRIBE_FROM_AUTH: "CALL_UNSUBSCRIBE_FROM_AUTH",
  SET_USER_START: "SET_USER_START",
  SET_USER_SUCCESS: "SET_USER_SUCCESS",
  SET_USER_FAILURE: "SET_USER_FAILURE",
};
